### ISSUE TITLE
The title always changes even if game_title is not specified. And Soku will not start if a Japanese title is specified.

### ISSUE THREAD

**Issue by stanak** [Giufinn/giuroll#1]
Hello, I'm midorist.
Is it possible to add a mode where the title is not changed, e.g. when game_title is not specified?

**Comment by Giufin** [comment]
To make diagnosing issues with users, by default the title contains the version, however unicode support was added with 74cf94d1ad9c8c8a4aff6b7ea623f723a4613278 , which I believe resolves this issue. If this is not enough please re-open the issue, I'll add the original requested option.
